import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Social-connection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Main container with minimum height to fill the screen */}
            <div className="min-h-screen">
              {/* Navbar component */}
              <Navbar />

              {/* Main content area with padding */}
              <main className="py-8">
                {/* Container for main content with max width and horizontal padding */}
                <div className="max-w-7xl mx-auto px-4">
                  {/* Grid layout for sidebar and main content */}
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    {/* Sidebar, hidden on small screens */}
                    <div className="hidden lg:block lg:col-span-3">
                      <SideBar />
                    </div>
                    {/* Main content area */}
                    <div className="lg:col-span-9">{children}</div>
                  </div>
                </div>
              </main>
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
